"use client";

import { CameraCapture } from "@/components/CameraCapture";
import { ResultsDisplay } from "@/components/ResultsDisplay";
import { ThemeToggle } from "@/components/theme-toggle";
import { useFaceAnalysisStore } from "@/app/lib/store";
import { Sparkles, Camera } from "lucide-react";

export default function Home() {
  const { result } = useFaceAnalysisStore();

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50 dark:from-gray-900 dark:via-purple-900/20 dark:to-blue-900/20">
      {/* Header */}
      <header className="relative">
        <div className="absolute top-4 right-4 z-10">
          <ThemeToggle />
        </div>
        
        <div className="text-center py-8 px-4">
          <div className="flex flex-col items-center space-y-4">
            <div className="flex items-center space-x-3">
              <div className="p-3 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full shadow-lg">
                <Sparkles className="h-8 w-8 text-white" />
              </div>
              <div className="text-left">
                <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-transparent">
                  FaceReader AI
                </h1>
                <p className="text-sm sm:text-base text-gray-600 dark:text-gray-400">
                  Powered by Google Gemini 2.5 Flash
                </p>
              </div>
            </div>
            
            <div className="max-w-2xl mx-auto space-y-2">
              <p className="text-lg text-gray-700 dark:text-gray-300">
                Discover insights about yourself through AI-powered face analysis
              </p>
              <div className="flex flex-wrap justify-center gap-2 text-sm">
                <span className="px-3 py-1 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 rounded-full">
                  🎭 Expression Analysis
                </span>
                <span className="px-3 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full">
                  💼 Career Insights
                </span>
                <span className="px-3 py-1 bg-pink-100 dark:bg-pink-900/30 text-pink-700 dark:text-pink-300 rounded-full">
                  ❤️ Love Guidance
                </span>
                <span className="px-3 py-1 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300 rounded-full">
                  💡 Life Tips
                </span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        <div className="space-y-8">
          {/* Camera or Results Section */}
          {!result ? (
            <div className="space-y-6">
              <div className="text-center space-y-2">
                <Camera className="h-12 w-12 text-purple-500 mx-auto" />
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-gray-100">
                  Ready to Discover Yourself?
                </h2>
                <p className="text-gray-600 dark:text-gray-400">
                  Allow camera access and take a photo to receive your personalized AI reading
                </p>
              </div>
              
              <CameraCapture />
            </div>
          ) : (
            <ResultsDisplay />
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="text-center py-8 px-4 border-t border-gray-200 dark:border-gray-700">
        <div className="space-y-2">
          <p className="text-sm text-gray-500 dark:text-gray-400">
            This analysis is for entertainment purposes and personal reflection. Results are generated by AI and should not be taken as professional advice.
          </p>
          <p className="text-xs text-gray-400 dark:text-gray-500">
            Powered by Google Gemini 2.5 Flash • Built with Next.js 14
          </p>
        </div>
      </footer>
    </div>
  );
}
